### ISSUE TITLE
FEAT: Add a .env file beforehand

### ISSUE THREAD

**Issue by Vyvy-vi** [eddiejaoude/stargate#1]
## Description-
Discord bot API token and other API keys should be added in a .env beforehand(rather than hard-coding while _testing_).

### Q) But Why?:
Ans- To prevent accidental pushing of keys

*this issue is on a lighter note:
CONTEXT: https://discord.com/channels/699608417039286293/801475116668026951/814615707773435945

**Comment by Vyvy-vi** [comment]
Yes, but the Github secrets don't work locally?

**Comment by nhcarrigan** [comment]
They also won't work if you deploy elsewhere. A `.env` file (for a node-js environment) is almost universally recognised by hosting platforms as your "secrets".

**Comment by eddiejaoude** [comment]
I think for local development we will use `.env` but for deployment we will use GitHub Secrets

**Comment by eddiejaoude** [comment]
So we need both ideas 👍 thank you 🤓
