### ISSUE TITLE
Feat: Create GitHub Action

### ISSUE THREAD

**Issue by Rahma-AlWadhahi** [eddiejaoude/stargate#10]
### Description 

It would be really helpful to add a GitHub action that will cover the following:

- Check lint issues
- Help with updating forked repo

**Comment by Vyvy-vi** [comment]
#10 refers this issue too
Here are some of the links from that issue:

Enable Dependabot security updates: https://github.com/nhcarrigan/code-snippets/blob/main/optional-workflows/dependabot.yml

Enable Node.js CI: https://github.com/nhcarrigan/code-snippets/blob/main/optional-workflows/node-ci.yml

**Comment by nhcarrigan** [comment]
#54 added the node CI

**Comment by eddiejaoude** [comment]
Thanks for raising @Rahma-AlWadhahi 👍 

PR for this merged in #54, I will close
