### ISSUE TITLE
Add a Table of Contents to the README

### ISSUE THREAD

**Issue by nhcarrigan** [eddiejaoude/stargate#108]
**Description**

As discussed on today's live stream, we should add a table of contents to the README.

This could actually be automated via a GitHub action paired with a custom script to parse the readme and generate the content. Alternatively, we could browse the actions marketplace for an existing tool. Either way, this should likely be automated.

**Screenshots**

**Additional Context**  

Join Eddie's discord community [here](https://discord.com/invite/jZQs6Wu)

**Comment by Vyvy-vi** [comment]
I think now, we could use github's new README Table of Contents feature?
![Screenshot 2021-03-29 at 4 24 02 PM](https://user-images.githubusercontent.com/62864373/112826953-51bbc680-90ab-11eb-8bd1-96d64358b9ef.png)

**Comment by nhcarrigan** [comment]
Ooo this is very new. And sleek.

I could complain about remaining platform agnostic and not relying on a specific UI for our documentation, but I think this works well enough for now.

**Comment by eddiejaoude** [comment]
Good timing from GitHub features 🤓
