### ISSUE TITLE
Add Table of Contents

### ISSUE THREAD

**Issue by galahad42** [eddiejaoude/stargate#109]
**Description**
Adding a Table of Contents would make the README cleaner and easier to navigate to different sections

Join Eddie's discord community [here](https://discord.com/invite/jZQs6Wu)

**Comment by eddiejaoude** [comment]
I think this feature is no longer needed, because GitHub have added the table of contents feature

<img width="1240" alt="Screenshot 2021-04-03 at 10 31 07" src="https://user-images.githubusercontent.com/624760/113474417-c609b780-9467-11eb-9286-6b573da8526d.png">
