### ISSUE TITLE
Workflows - CI for GitHub Actions

### ISSUE THREAD

**Issue by nhcarrigan** [eddiejaoude/stargate#11]
As we establish the code, we'll want to enable CI such as verifying the lint, build, and tests all pass.

Enable Dependabot security updates: https://github.com/nhcarrigan/code-snippets/blob/main/optional-workflows/dependabot.yml

Enable Node.js CI: https://github.com/nhcarrigan/code-snippets/blob/main/optional-workflows/node-ci.yml

**Comment by nhcarrigan** [comment]
Closing as duplicate of #10

**Comment by eddiejaoude** [comment]
Yes we will need those 👍
