### ISSUE TITLE
Add "Made with Love with/by ..." at the end of readme.md

### ISSUE THREAD

**Issue by schmelto** [eddiejaoude/stargate#110]
Join Eddie's discord community [here](https://discord.com/invite/jZQs6Wu)

**Comment by srinath1412001** [comment]
Example
![example](https://user-images.githubusercontent.com/47494475/112034289-51c83d80-8b64-11eb-8dd6-1769484aaa20.png)

**Comment by schmelto** [comment]
@srinath1412001 thanks for adding the screenshot 👍🏼

**Comment by eddiejaoude** [comment]
Great idea 👍

**Comment by adityaraute** [comment]
Who's working on this?
