### ISSUE TITLE
Add 'made with love and ..'

### ISSUE THREAD

**Issue by komalswami** [eddiejaoude/stargate#111]
**Description**

**Screenshots**

**Additional Context**  

Join Eddie's discord community [here](https://discord.com/invite/jZQs6Wu)

**Comment by srinath1412001** [comment]
Duplicate issue
Already opened here #110

**Comment by eddiejaoude** [comment]
Thanks for raising @komalswami 👍 

Thank you for triaging @srinath1412001 👍
