### ISSUE TITLE
Suggestion on creating separate Phase 1 Document

### ISSUE THREAD

**Issue by orama254** [eddiejaoude/stargate#113]
**Description**
The Phase 1 text appears lower on the readme file.

It's suggested that you create a new file for it then link the file to the readme

*Also*

The phase 1 goals should be mapped onto the user stories and Kanbaned on the projects tab (as suggested by @nhcarrigan )

**Additional Context**  

check out the context from the stream starting at [47:00](https://youtu.be/djpH43hsOJI?t=2820) to 49:00

Join Eddie's discord community [here](https://discord.com/invite/jZQs6Wu)

**Comment by eddiejaoude** [comment]
Thank you 👍
