### ISSUE TITLE
Typo in the README.md

### ISSUE THREAD

**Issue by Sfitzg** [eddiejaoude/stargate#119]
**Description**
There is a typo in the `README.md` file under the Github actions section for Docs Status 
it reads 

> checkout source files, ~~duild~~ doc files, deploy  

should be

> Checkout source files, build doc files, deploy  

**Screenshots**
<img width="873" alt="Screenshot 2021-04-06 at 00 11 14" src="https://user-images.githubusercontent.com/5940631/113633186-c7f09800-966c-11eb-873c-22e3d95219de.png">

**Additional Context**  

Join Eddie's discord community [here](https://discord.com/invite/jZQs6Wu)

**Comment by eddiejaoude** [comment]
Thank you for raising the issue 👍
