### ISSUE TITLE
Technologies Used!

### ISSUE THREAD

**Issue by reapedjuggler** [eddiejaoude/stargate#12]
Create a `.md` file listing the technologies we are using
For example - **typescript**

Suggestion: A ordered List would be a good way to list them. 
Feel free to ask any doubts :)

**Comment by eddiejaoude** [comment]
I think the technologies will be:

- Typescript
- Stargate
- ...

**Comment by reapedjuggler** [comment]
Can you add some relevant labels to the issue, I think it would be helpful : D

**Comment by FemiOluwadamilola** [comment]
can JavaScript also be use as part of the technologies? some of us only code on javascript
