### ISSUE TITLE
Documentation regarding docker run

### ISSUE THREAD

**Issue by rafaquelhodev** [eddiejaoude/stargate#126]
**Description**

Hi all! I tried to run stargate locally using docker following the documentation, but the container did not found the enviroment variables. The command I found in the documentation was `docker run -p 3000:3000 --name stargatebot -d eddiejaoude/stargate`

Then I managed to run with docker passing the env file with `docker run -p 3000:3000 --env-file ./.env --name stargatebot -d eddiejaoude/stargate`

Am I missing some step to run with docker?

Join Eddie's discord community [here](https://discord.com/invite/jZQs6Wu)

**Comment by eddiejaoude** [comment]
Hi @rafaquelhodev, apologies for the slow reply.

There is still code in branches at the moment, we are also migrating some repos together, including moving the data later to an API https://github.com/EddieHubCommunity/api 

The default branch `main` has the foundations for the project, but is still not ready to be used.

Sorry for the confusion.

**Comment by rafaquelhodev** [comment]
Hi @eddiejaoude , no worries!

**Comment by eddiejaoude** [comment]
Hi @rafaquelhodev , we have split this project into 2, the Discord bot `EddieBot` and the `api` project into the EddieHubCommunity Org http://github.com/EddieHubCommunity/

Come and join us there were we can collaborate 🤓

**Comment by rafaquelhodev** [comment]
Great! I'm gonna check it out!

**Comment by eddiejaoude** [comment]
Awesome! Any questions let us know in Discord and we can help 🤓 http://discord.eddiehub.org
