### ISSUE TITLE
Info about stargate on social media platforms

### ISSUE THREAD

**Issue by mrunankpawar** [eddiejaoude/stargate#13]
If we can share deep info about what actually stargate is on social media platforms then we can get some great suggestions from others as well which can be helpful.

**Comment by eddiejaoude** [comment]
Thanks for the suggestion 👍

**Comment by eddiejaoude** [comment]
@mrunankpawar we should definitely do this 👍 I think I will close this issue and more specific issues can be raise. Feel free to raise more issues 🟩
