### ISSUE TITLE
Add CONTRIBUTING.md and CODE OF CONDUCT

### ISSUE THREAD

**Issue by starlightknown** [eddiejaoude/stargate#18]
Adding contributing.md to help potential project contributors with a short guide to how they can help with your project

**Comment by muthuannamalai12** [comment]
Can I do it

**Comment by Vyvy-vi** [comment]
Yes, you can @muthuannamalai12 (I think if no one's working on it rn)

**Comment by Vyvy-vi** [comment]
Copying relevant info from #25 over here:
> We can have these links for the following in CONTRIBUTION.md file
1.We can add Github documentation links for
i). Getting started with Git and GitHub
ii). Forking a Repo
iiI). Cloning a Repo
iv). How to create a Pull Request
2.Also, we can give the links for git installation
3.We can also add Style Guides for Git Commit Messages
These things will help people new to opensource understand clearly on how to create an issue and how to create a PR.

creds- @muthuannamalai12
