### ISSUE TITLE
We could move this repo to EddieHub Organisation 

### ISSUE THREAD

**Issue by srinath1412001** [eddiejaoude/stargate#19]
We could move this repository to EddieHub Organisation (within Github) to make the project visible to a wider crowd.

**Comment by eddiejaoude** [comment]
Oh love this idea 👍 💪

**Comment by Vyvy-vi** [comment]
​(but not right now)
​Eddie, our remotes have upstreams linked to your account

**Comment by eddiejaoude** [comment]
yep, not right now 👍

**Comment by adityaraute** [comment]
Well then when? Wouldn't be too hard to change the upstreams, right?

**Comment by eddiejaoude** [comment]
Soon. There will be some other config changes too, but yes it won't be difficult. I am just holding off for the moment.

**Comment by ghost** [comment]
@eddiejaoude can you fix what the stale bot did? And btw when will we move this repo to EddieHub org, I can fix #45 after that as well since I can propose the project to the organization?

**Comment by eddiejaoude** [comment]
This repo has been replaced with 2 repos in our GitHub Org, so the move is no longer required.

- https://github.com/EddieHubCommunity/api
- https://github.com/EddieHubCommunity/EddieBot
