### ISSUE TITLE
EddieBotMap 

### ISSUE THREAD

**Issue by mrunankpawar** [eddiejaoude/stargate#22]
Creating a map which is just similar to Snapchat and we can add events or hackathons to the Map so that folks can stay updated where the hackathons and events are taking place on the map

**Comment by mrunankpawar** [comment]
![snapmap](https://user-images.githubusercontent.com/65391854/109338734-a8f03080-788c-11eb-8f31-6c92867b55d1.png)

**Comment by Vyvy-vi** [comment]
Interesting-!

**Comment by eddiejaoude** [comment]
This is a great idea for the future 👍

**Comment by Vyvy-vi** [comment]
I suppose this also overlaps with EddieBotMap a bit.
Could you raise a discussion for this on the org?

**Comment by eddiejaoude** [comment]
Yep there are some overlaps - we will see if we can merge some of these ideas/projects/repo etc in the near future 🤓

**Comment by eddiejaoude** [comment]
This will be done in the Live Map project https://github.com/EddieHubCommunity/EddieBotLive
