### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by muthuannamalai12** [eddiejaoude/stargate#25]
We can have these links for the following in CONTRIBUTION.md file
1.We can add Github documentation links for
i). Getting started with Git and GitHub
ii). Forking a Repo
iiI). Cloning a Repo
iv). How to create a Pull Request
2.Also, we can give the links for git installation
3.We can also add Style Guides for Git Commit Messages
These things will help people new to opensource understand clearly on how to create an issue and how to create a PR.

**Comment by Vyvy-vi** [comment]
partially mentioned in #18
