### ISSUE TITLE
Link to Stargate

### ISSUE THREAD

**Issue by adityaraute** [eddiejaoude/stargate#3]
Since a lot of folks might not be aware about Stargate, add a link to the repo in the README file.

**Comment by jai-dewani** [comment]
Here is the link to stargate -> https://stargate.io/

**Comment by jai-dewani** [comment]
We can also add a short intro if needed, this one is straight off their website 
> Stargate is an open source data gateway that sits between your app and your databases. Stargate brings together an API platform and data request coordination code into one OSS project.

**Comment by adityaraute** [comment]
> Here is the link to stargate -> https://stargate.io/

I meant the link to their GitHub repository as well

**Comment by eddiejaoude** [comment]
Thank you for raising the issue 👍
