### ISSUE TITLE
Add some Linter checks to the bot  

### ISSUE THREAD

**Issue by reapedjuggler** [eddiejaoude/stargate#31]
Suggestion: As the projects proceeds we can add some linter checks to the bot so as to reduce errors and improve the overall quality of code 

You can read more about Linter here
[What is Linter](https://sourcelevel.io/blog/what-is-a-linter-and-why-your-team-should-use-it)

**Comment by Vyvy-vi** [comment]
duplicate of #4
related to #10 and #11

**Comment by reapedjuggler** [comment]
Had a look, Thank you for pointing out : D

**Comment by eddiejaoude** [comment]
Thank you for creating the issue and triaging 👍 great team work 💪
