### ISSUE TITLE
Adding Stale Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [eddiejaoude/stargate#36]
I would like to add a stale bot that Automatically close stale Issues and Pull Requests that tend to accumulate during a project.

**Comment by Vyvy-vi** [comment]
ref: #10

**Comment by adityaraute** [comment]
It's the first day of the repo and y'all wanna add Stale Bot 😂 

not a bad idea though

**Comment by Vyvy-vi** [comment]
Idk stalebot has been annoying as of late :joy:
We just keep re-opening the issues/PRs

**Comment by eddiejaoude** [comment]
PR merged 👍

**Comment by Vyvy-vi** [comment]
addressed by #40

**Comment by eddiejaoude** [comment]
Thanks @Vyvy-vi 👍
