### ISSUE TITLE
Discord Bot Feature: Command to Add Social Links

### ISSUE THREAD

**Issue by yalematta** [eddiejaoude/stargate#37]
Set Social Links
/social github = "https://github.com/yalematta"
/social twitter = "https://twitter.com/yalematta"

**Comment by Vyvy-vi** [comment]
I think the `/bio` command is meant for that purpose
ref: #29

**Comment by Vyvy-vi** [comment]
This can be added in the bio command in this way-
```
person> /bio add github https://github.com/yalematta
bot> added bio
```

**Comment by yalematta** [comment]
As mentioned by @Vyvy-vi, this is part of the /bio command.

**Comment by eddiejaoude** [comment]
Thank you for creating the issue and triaging 👍 great team work 💪

**Comment by eddiejaoude** [comment]
Would separate commands make it easier or harder?

```
/bio set description <string>
/bio set github  <string>
...
```

or

```
/bio description  <optional-string>
/github <optional-string>
...
```

What do you think?
