### ISSUE TITLE
Custom Introduction video for Stargate 

### ISSUE THREAD

**Issue by KhushiSharma22** [eddiejaoude/stargate#38]
We can create a custom video for Stargate to help people get a better idea of Stargate and what this project is about: 

1. Adding custom info about Stargate 
2. Adding necessary details about the project 
3. Maybe we can use some animations just to make it a little bit fun

**Comment by Vyvy-vi** [comment]
Would be great-!
(Eddie's video for the next week?)
ref: @eddiejaoude

**Comment by reapedjuggler** [comment]
We can also add some custom slides on Stargate apart from videos?

**Comment by FemiOluwadamilola** [comment]
this will be great  !!!

**Comment by eddiejaoude** [comment]
Great idea and suggestions 👍 

Anything else we should include in addition to @KhushiSharma22 's suggestions?
