### ISSUE TITLE
Discord Bot Feature: Command to Add Timezone

### ISSUE THREAD

**Issue by yalematta** [eddiejaoude/stargate#39]
Add Timezone
--------------

/timezone PST
/timezone EST etc.

**Comment by Vyvy-vi** [comment]
I think instead of timezone terms, we should use "Timezone Area"
(Daytime-saving makes timezones weird in a few places)

**Comment by eddiejaoude** [comment]
Can you give some examples of what would be good to use?

**Comment by Vyvy-vi** [comment]
I think the following might could good-
```
/timezone Europe/uk
/timezone +0:00
/timezone +5:00
```
offsets and area based?
