### ISSUE TITLE
Set Up Contributor Tooling

### ISSUE THREAD

**Issue by nhcarrigan** [eddiejaoude/stargate#4]
Let's add tooling such as `eslint`, `husky`, `prettier` to ensure code standards as we accept contributions from members.

Here's my default TypeScript tooling: https://github.com/nhcarrigan/code-snippets/tree/main/node-ts-config

**Comment by eddiejaoude** [comment]
Yep, we should add these from the beginning 👍

**Comment by nhcarrigan** [comment]
Closed in #54
