### ISSUE TITLE
Addition of relevant data flow diagrams on README.md using Mermaid

### ISSUE THREAD

**Issue by patel-himanshu** [eddiejaoude/stargate#43]
A data flow diagram detailing the state of data flow between the user, Stargate and Cassandra, by making use of [Mermaid](https://mermaid-js.github.io/mermaid/#/).

**Comment by eddiejaoude** [comment]
What diagram types could be useful?

- Sequence diagram  https://mermaid-js.github.io/mermaid/#/sequenceDiagram
- Relationship diagram https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram
- ?
