### ISSUE TITLE
Using Conventional Commits

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [eddiejaoude/stargate#49]
[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by Vyvy-vi** [comment]
Yes, it would be great to add that to the `CONTRIBUTING.md` :+1:
ref: #28

**Comment by Prathamesh-Shanbhag** [comment]
Yes! Thank you for mentioning it!

**Comment by eddiejaoude** [comment]
Also good to use Huski as a pre-commit hook too
