### ISSUE TITLE
make the intro video in the Readme.md load on a different tab

### ISSUE THREAD

**Issue by FemiOluwadamilola** [eddiejaoude/stargate#51]
making the intro video in the readme load on a different tab would be great !!! because when you click on the video link it takes you out of github to youtube!

**Comment by AllanRegush** [comment]
I don't think this is possible. GitHub sanitises all HTML in markdown to prevent XSS attacks. If you want a new tab  - CTRL+CLICK.

**Comment by FemiOluwadamilola** [comment]
Thanks  !!!

**Comment by Vyvy-vi** [comment]
I think we could maybe set up a brief GIF and just link the video

**Comment by CreaTorAlexander** [comment]
I can do the gif 👋

**Comment by FemiOluwadamilola** [comment]
that would be nice @CreaTorAlexander
