### ISSUE TITLE
Live stream poker planning for story points on issues.

### ISSUE THREAD

**Issue by AllanRegush** [eddiejaoude/stargate#68]
**Description**

I think there should be a live stream planning the story points.

Join Eddie's discord community [here](https://discord.com/invite/jZQs6Wu)

**Comment by adityaraute** [comment]
Did someone say Poker?

**Comment by eddiejaoude** [comment]
Great idea @AllanRegush 👍 

A live stream with 4-5 people going through the issues, discussing them and voting on them with story points would be great to show how real Agile projects do it 👍 

We could use an online Agile poker board to have every vote and make it visual for the live stream.

Potential people to be on the live stream
- @nhcarrigan 
- @AllanRegush 
- Pieter from DataStax
- Eddie

**Comment by adityaraute** [comment]
Okay I might need more explanation than that. First up — what's story points? I think I have heard it in case of Agile but not sure. (That was user story). 

Also what's poker got to do with all this?

**Comment by eddiejaoude** [comment]
**story points** are how much effort/risk, not time the story (feature) will need. The higher the points more the more unknown / risk there is. I would rather have 8 stories with 1 point each, than 1 story with 8 points.

To point stories, these are done as a team exercise, where each team member gets cards containing Fibonacci sequence. When poker planning, if there is a difference in points between team members (there always is as the beginning of a new team, as it takes time to get on the same page), for example one team member points it 3 points and another 8 points, these members can present why they gave it that score, then the team can re-vote again.

**Comment by adityaraute** [comment]
Yes that helps. let's do it.
