### ISSUE TITLE
CI Actions badges

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/stargate#71]
Badges in README for

- import labels
- node ci
- publish docker image

https://github.com/eddiejaoude/stargate/tree/main/.github/workflows

Example badge

[![GitHub Super-Linter](https://github.com/eddiejaoude/stargate/workflows/Node.js%20CI/badge.svg)](https://github.com/eddiejaoude/stargate/actions/workflows/node-ci.yml)

```
[![GitHub Super-Linter](https://github.com/<OWNER>/<REPOSITORY>/workflows/Lint%20Code%20Base/badge.svg)](https://github.com/marketplace/actions/super-linter)
```

**Comment by CreaTorAlexander** [comment]
I can work on this but I am uncertain how the badges for import labels and publish docker image should look like.

For docker image should it be the system that is running like

```
[docker image][ubuntu-latest]

       ^^ 
The Badge

```

**Comment by eddiejaoude** [comment]
Thanks @CreaTorAlexander 👍 

I am not sure either 😂 - I think this is one of those things, that will get little improvements / tweaks as we go along. Feel free to do what you think is best and I think that will be a great starting point 🤓

**Comment by MitanshuShaBa** [comment]
There has been a lot of time since there is any activity here. I would like to work on this.
