### ISSUE TITLE
Add Issue and PR templates

### ISSUE THREAD

**Issue by nhcarrigan** [eddiejaoude/stargate#8]
We should implement issue templates and a pull request template.

We can consider using the Creative Commons Open Source Labels: https://opensource.creativecommons.org/contributing-code/repo-labels/

**Comment by Vyvy-vi** [comment]
Issue templates would be great-!
We can use the ones from https://github.com/EddieHubCommunity/EddieBot/tree/develop/.github/ISSUE_TEMPLATE
(after editing some data in there)

**Comment by nhcarrigan** [comment]
This JS snippet, when run in your browser console, will add the labels to your repo: https://raw.githubusercontent.com/nhcarrigan/code-snippets/main/transfer-github-labels/import.js

Please note you should delete the existing labels manually first.

**Comment by Vyvy-vi** [comment]
Thanks, for this, nick :)

**Comment by BOLT04** [comment]
Amazing idea @nhcarrigan 💯 💯, I didn't know about that labels standard so I learned something new today 😄.
Plus the JS script to add the labels, simply amazing 😃. Thank you for your suggestion!

**Comment by nhcarrigan** [comment]
This can be closed now, I believe.
