### ISSUE TITLE
Github Actions table in README

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/stargate#82]
markdown table in the readme explain what Action we have with the following columns

- badge (from #71)
- name
- triggers
- results

**Comment by kaiwalyakoparkar** [comment]
I would like to work on this. Could  you please guide me?

**Comment by MitanshuShaBa** [comment]
@kaiwalyakoparkar you can take the badges from #105 

You can read how to make a markdown table from [Organizing information with tables
](https://docs.github.com/en/github/writing-on-github/organizing-information-with-tables)

**Comment by kaiwalyakoparkar** [comment]
Thank you very much @MitanshuShaBa. May I start working on it or wait for the assignment

**Comment by MitanshuShaBa** [comment]
You can start working on it I guess

**Comment by kaiwalyakoparkar** [comment]
Ok thank you!

**Comment by kaiwalyakoparkar** [comment]
@MitanshuShaBa Could you please guide me on how can I add the required tags?

**Comment by kaiwalyakoparkar** [comment]
@eddiejaoude, @MitanshuShaBa What should I add-in name, triggers, and results?

**Comment by MitanshuShaBa** [comment]
Go to .github/workflows and read every yaml file and understand how each action works. And fill the information accordingly

**Comment by kaiwalyakoparkar** [comment]
Ok thanks I'll have a look at it

**Comment by kaiwalyakoparkar** [comment]
@MitanshuShaBa Should I add this table after Technologies used section?
