### ISSUE TITLE
Write CRUD services to the Stargate database

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [eddiejaoude/stargate#83]
- add http client
- typescript interfaces for data
- authentication 
- service to manage CRUD

**Comment by eddiejaoude** [comment]
dependent on #76

**Comment by nhcarrigan** [comment]
dependent on #67

**Comment by nhcarrigan** [comment]
not 76 :)

**Comment by eddiejaoude** [comment]
Oops you are right, thanks @nhcarrigan 👍
