### ISSUE TITLE
Docker Compose for local dev environment?

### ISSUE THREAD

**Issue by stemount** [eddiejaoude/stargate#86]
**Description**

Ticket needs grooming... `docker run` makes a bit of a mess if people already have existing Cassandra(?) / Stargate instances I am guessing. 

it could also set up the networking for a local dev as well and even be recycled for configuration of the k8s file if it is one image etc etc

Join Eddie's discord community [here](https://discord.com/invite/jZQs6Wu)

**Comment by eddiejaoude** [comment]
Great idea 👍
