### ISSUE TITLE
Kubernetes workflow to update kubernetes secrets from GitHub

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/stargate#94]
From issue https://github.com/eddiejaoude/stargate/issues/72#issuecomment-799640072 

- update kubernetes workflow to update secrets from GitHub

```
export TMP_SECRET_YAML_FILE=secret.yaml
kubectl create secret generic discord-bot-secret --from-literal=DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} --dry-run -o yaml > $TMP_SECRET_YAML_FILE
kubectl apply -f secret.yaml
rm $TMP_SECRET_YAML_FILE
```

- document how to create a new secret on kubernetes

**Comment by Divyaansh313** [comment]
What exactly do we want to do here ?
Just add a document on how to create secret on K8s ?

**Comment by MitanshuShaBa** [comment]
Here is what I think we have to do

- [ ] make a github action which runs on some interval eg: every 24 hours or anytime a secret is changed(I don't know if there is a trigger like this)
- [ ] extract the secret token from github secrets
- [ ] make a secret.yaml file which will create a kubernetes secret
- [ ] apply these changes of secrets using kubectl
- [ ] remove the secret.yaml file to avoid leaking of secrets

Is this right?

**Comment by eddiejaoude** [comment]
Thank you for collaborating. 

- [ ] I think the simplest solution, is for it to run in an existing action every time. It can be appended to this section `https://github.com/eddiejaoude/stargate/blob/main/.github/workflows/docker.yml#L70` 
- [ ] then add documentation on how to add another secret, as there could be multiples

I learnt this from Sid. @sidpalas do you have a video on this on your YouTube channel?
