### ISSUE TITLE
Create Release didn't happen but it didn't fail

### ISSUE THREAD

**Issue by VikasHanumegowda** [eddiejaoude/stargate#95]
While deploying, create release failed silently without notifying us about the failure @~54:00 of this video - https://www.youtube.com/watch?v=y0COd8fDjac because the release name/tag of v0.5.0 was already taken already.

**Comment by VikasHanumegowda** [comment]
Okay, the main branch was protected from the action you were trying to make to create a release. (Previously, it had worked for you 'cause you were trying it in a different branch(not main branch)). Hope this comment is helpful for a solution.

**Comment by eddiejaoude** [comment]
Thank you @VikasHanumegowda 👍 - yep the branch was protected which caused me issues 🤦‍♂️ 

Sorry for my slow response. I will close this issue as it is now resolved
